# Database configuration
database:
  # Available database types at the moment:
  # - sqlite
  # - mysql
  type: "sqlite"
  # SQLite-related settings
  sqlite:
    # The name of the SQLite database. The file will be created under
    # plugins/Waypoint/{filename}
    filename: "waypoint.db"
  # MySQL-related settings
  mysql:
    # The host
    host: 'localhost'
    # The port
    port: 3306
    # The name of the database
    database: 'database'
    username: 'username'
    password: 'password'
    # Extra query parameters so that certain optimizations can be made.
    query_params: "?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true"
    # Connection pool-related settings
    pool:
      # Maximum size of the pool (including active and inactive connections).
      size: 15
      # This many connections will be kept alive on the pool ready to go.
      minimum_idle: 10
      # Number of seconds, before a connection is marked for closing. This prevents
      # inactive connections from lingering indefinitely in the pool taking up resources.
      max_lifetime: 30
      # Number of seconds to wait for a connection to become available, before throwing
      # an error.
      connection_timeout: 5

# Hologram configuration
hologram:
  # The gap between hologram lines.
  line_padding: 0.3
  # The offset from the actual waypoint location.
  top_offset: 2.0

navigation:
  # Particle stream (navigation indicator) settings.
  particle:
    # The color of the navigation particle indicators. The value has to be either a
    # hexadecimal number representing a color, or a name from the following list:
    # - white, silver, gray, black, red, maroon, yellow, olive, lime, green, aqua, teal
    #   blue, navy, fuchsia, purple, orange
    color: "#3ac930"
    # The size of the particles. 5 is the default - and recommended - value.
    size: 5
    # The number of particles to spawn for each position.
    count: 10
    # This value is added to the current y coordinate of the player. The result is
    # a taller - easier to notice - particle column.
    y_offset: 30
    # Controls how the dense the particle column will be. The lower the number is,
    # the denser the particle column is. The minimum value (and maximum density) is 1.
    density: 2

  indicator:
    # The distance is calculated from the player's current location.
    distance_multiplier: 20
    # Spawn a new indicator, if the player gets further from the currently
    # visible indicator than this value.
    max_distance: 40
    # Spawn a new indicator, if the player gets closer to the currently
    # visible indicator than this value.
    arrival_distance: 5

  # If the player is closer to the waypoint (in blocks) than this number,
  # the navigation will not start.
  min_required_distance: 15
  # If the player gets to a distance (in blocks) of the value below (or closer),
  # the navigation will stop.
  arrival_distance: 15
