# Database configuration
database:
  # Available database types at the moment:
  # - sqlite
  type: "sqlite"
  # SQLite-related settings
  sqlite:
    # The name of the SQLite database. The file will be created under
    # plugins/Waypoint/{filename}
    filename: "waypoint.db"
  # MySQL-related settings
  mysql:
    host: 'host'
    port: 0
    database: 'database'
    username: 'username'
    password: 'password'
