name: "Waypoint"
main: "com.tomushimano.waypoint.WaypointPlugin"
bootstrapper: "com.tomushimano.waypoint.WaypointBootstrap"
version: "${version}"
api-version: "1.21"
authors: [ "tomushimano" ]
website: "https://github.com/adamtomi/Waypoint"
